imports:
    - { resource: "services/gateway_configuration.yml" }
    - { resource: "services/gateway_factory.yml" }
#    - { resource: "services/provider.yml" }


services:
    Sbarbat\SyliusSagepayPlugin\Action\Integrations\Form\CaptureAction:
        arguments:
            - '@sylius.province_naming_provider'
        public: true
        tags:
            - { name: payum.action, factory: sagepay, alias: payum.action.capture}
